version: "3.3"
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  

  backend:
    image: irinapoltarykhina/user_management:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    image: irinapoltarykhina/user_management_front:latest
    restart: always
    volumes:
      - ../frontend/:/app/build/
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000


volumes:
  static_value:
  media_value:
  postgres_data: